on:
  push:
    branches:
    - master

name: Deploy to GitHub Pages

jobs:
  deploy:
    steps:
    - name: snack-og-image
      uses: planetarium/snack.planetarium.dev/.github/actions/snack-og-image
    - name: hugo-deploy-gh-pages
      uses: khanhicetea/gh-actions-hugo-deploy-gh-pages@master
      env:
        GIT_DEPLOY_KEY: ${{ secrets.GIT_DEPLOY_KEY }}
        HUGO_VERSION: '0.53'
